services:
  dbops:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env.example
    volumes:
      - ../config:/app/config:ro
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    env_file:
      - ../.env.example
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DBOPS_SQL_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
